
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

INSERT INTO <urn:sparql:tests:insert:informative> 
  {
    <#book1> <http://purl.org/dc/elements/1.1/title> "Fundamentals of Compiler Design" .
    <#book1> <http://purl.org/dc/elements/1.1/date>  "1977-01-01T00:00:00-02:00"^^xsd:dateTime .

    <#book2> <#price> 42 .
    <#book2> <http://purl.org/dc/elements/1.1/title>   "David Copperfield" .
    <#book2> <http://purl.org/dc/elements/1.1/creator> "Edmund Wells" .
    <#book2> <http://purl.org/dc/elements/1.1/date>    "1948-01-01T00:00:00-02:00"^^xsd:dateTime .
  }